name: asistapp
description: "AplicaciÃ³n de registro de asistencia escolar con escaneo QR"
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  google_sign_in: ^6.3.0
  provider: ^6.1.2
  go_router: ^14.8.1
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: false