name: taskmonitoring
description: "AplicaciÃ³n de monitoreo de tareas con Gemini AI y Firebase"
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.6
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.0
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: false