name: taskmonitoring
description: "AplicaciÃ³n de monitoreo de tareas con Gemini AI y Firebase"
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.4.10
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_generative_ai: ^0.4.6

dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1

flutter:
  uses-material-design: false