name: nueva_app
description: "Nueva aplicaciÃ³n con Gemini AI"
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.6

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: false